[phases.setup]
nixPkgs = ['php82', 'composer', 'php82Extensions.pdo_sqlite', 'php82Extensions.gd', 'php82Extensions.curl']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction --no-scripts'
]

[phases.build]
cmds = [
  'php artisan config:cache',
  'php artisan route:cache'
]

[start]
cmd = 'mkdir -p database && touch database/database.sqlite && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'

